# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        dbt-version:
        - 0.18.0
        - 0.18.1
        - 0.19.0
        exclude:
          # dbt release candidate doesn't install in Python 3.9
          - python-version: 3.9
            dbt-version: 0.19.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install dbt==${{ matrix.dbt-version }}
        poetry install
    - name: Run tests
      run: |
        poetry run pytest tests
